name: Post leaderboard on Slack

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
  schedule:
    #  runs Monday to Saturday at 7 am UTC
    - cron: '0 18 * * *'

env:
  LEADERBOARD_ID: ${{secrets.LEADERBOARD_ID}}
  SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL}}
  SESSION_ID: ${{secrets.SESSION_ID}}

jobs:
  post-leaderboard:
    runs-on: ubuntu-latest
    steps:
      # run E2E tests
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: post leaderboard
        run: |
          env | grep {LEADERBOARD_ID,SLACK_WEBHOOK,SESSION_ID}
          env python leaderboard.py
